In [462]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1dM9MQJwUSFKfOnKzOqbGYIv3DMLC7xt2')

In [463]:
!pip install jovian --upgrade --quiet

In [464]:
import numpy as np
import pandas as pd
import torch


In [465]:
data=pd.read_csv('/USA_Housing.csv')

In [466]:
data.head(5)

Avg. Area Income  ...                                            Address
0      79545.458574  ...  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1      79248.642455  ...  188 Johnson Views Suite 079\nLake Kathleen, CA...
2      61287.067179  ...  9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3      63345.240046  ...                          USS Barnett\nFPO AP 44820
4      59982.197226  ...                         USNS Raymond\nFPO AE 09386

[5 rows x 7 columns]

In [467]:
data.drop('Address',axis='columns',inplace=True)

In [468]:
data.head(4)

Avg. Area Income  Avg. Area House Age  ...  Area Population         Price
0      79545.458574             5.682861  ...     23086.800503  1.059034e+06
1      79248.642455             6.002900  ...     40173.072174  1.505891e+06
2      61287.067179             5.865890  ...     36882.159400  1.058988e+06
3      63345.240046             7.188236  ...     34310.242831  1.260617e+06

[4 rows x 6 columns]

In [469]:
target=data['Price']

In [470]:
data.head()

Avg. Area Income  Avg. Area House Age  ...  Area Population         Price
0      79545.458574             5.682861  ...     23086.800503  1.059034e+06
1      79248.642455             6.002900  ...     40173.072174  1.505891e+06
2      61287.067179             5.865890  ...     36882.159400  1.058988e+06
3      63345.240046             7.188236  ...     34310.242831  1.260617e+06
4      59982.197226             5.040555  ...     26354.109472  6.309435e+05

[5 rows x 6 columns]

In [471]:
target

0       1.059034e+06
1       1.505891e+06
2       1.058988e+06
3       1.260617e+06
4       6.309435e+05
            ...     
4995    1.060194e+06
4996    1.482618e+06
4997    1.030730e+06
4998    1.198657e+06
4999    1.298950e+06
Name: Price, Length: 5000, dtype: float64

In [472]:
input=data

In [473]:
input.head()

Avg. Area Income  Avg. Area House Age  ...  Area Population         Price
0      79545.458574             5.682861  ...     23086.800503  1.059034e+06
1      79248.642455             6.002900  ...     40173.072174  1.505891e+06
2      61287.067179             5.865890  ...     36882.159400  1.058988e+06
3      63345.240046             7.188236  ...     34310.242831  1.260617e+06
4      59982.197226             5.040555  ...     26354.109472  6.309435e+05

[5 rows x 6 columns]

In [474]:
target.head()

0    1.059034e+06
1    1.505891e+06
2    1.058988e+06
3    1.260617e+06
4    6.309435e+05
Name: Price, dtype: float64

In [475]:
import jovian

In [476]:
jovian.commit(project='linear-regression')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rhuthuhegde/linear-regression


'https://jovian.ai/rhuthuhegde/linear-regression'

In [477]:
data['Price']=target

In [478]:
data.head()

Avg. Area Income  Avg. Area House Age  ...  Area Population         Price
0      79545.458574             5.682861  ...     23086.800503  1.059034e+06
1      79248.642455             6.002900  ...     40173.072174  1.505891e+06
2      61287.067179             5.865890  ...     36882.159400  1.058988e+06
3      63345.240046             7.188236  ...     34310.242831  1.260617e+06
4      59982.197226             5.040555  ...     26354.109472  6.309435e+05

[5 rows x 6 columns]

In [479]:
target=torch.tensor(target.values)

In [480]:
# target=torch.log(target)

In [481]:
target

tensor([1059033.5579, 1505890.9148, 1058987.9879,  ..., 1030729.5832,
        1198656.8724, 1298950.4803], dtype=torch.float64)

In [482]:
target=torch.log(target)

In [483]:
input=torch.tensor(input.values)

In [484]:
input=torch.log(input)

In [485]:
# input=torch.log(input)

In [486]:
input

tensor([[11.2841,  1.7375,  1.9472,  1.4085, 10.0470, 13.8729],
        [11.2803,  1.7922,  1.9067,  1.1282, 10.6010, 14.2249],
        [11.0233,  1.7692,  2.1416,  1.6351, 10.5155, 13.8728],
        ...,
        [11.0571,  1.9811,  1.5697,  0.7561, 10.4123, 13.8458],
        [11.1273,  1.7110,  1.9643,  1.6938, 10.6602, 13.9967],
        [11.0900,  1.7905,  1.9158,  1.4036, 10.7472, 14.0771]],
       dtype=torch.float64)

converting the pandas dataframe into pytorch tensor

In [487]:
target.shape

torch.Size([5000])

In [488]:
input.shape

torch.Size([5000, 6])

In [489]:
jovian.commit(project='linear-regression')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rhuthuhegde/linear-regression


'https://jovian.ai/rhuthuhegde/linear-regression'

creating the random weights and biases

In [490]:
w=torch.randn(1,6,requires_grad=True,dtype=torch.float64)
b=torch.randn(1,requires_grad=True,dtype=torch.float64)

In [491]:
print(w)
print(w.shape)

tensor([[-0.2960, -0.0825,  0.2563,  0.5315,  0.3309,  1.0002]],
       dtype=torch.float64, requires_grad=True)
torch.Size([1, 6])


In [492]:
b

tensor([-1.0228], dtype=torch.float64, requires_grad=True)

In [493]:
def prediction(input):
  pred=input@w.t()+b
  return pred

In [494]:
def mse(pred,target):
  diff=pred-target
  loss=torch.sum(diff*diff)/diff.numel()
  return loss

In [495]:
# def gradient(w,b,loss):
#   lr=0.001
#   loss.backward()
#   with torch.no_grad():
#     w-=w.grad*lr
#     b-=b.grad*lr
#     w.grad.zero_()
#     b.grad.zero_()
#   return w,b

In [496]:
err=[]
for i in range(1000):
  pred=prediction(input)
  error=mse(pred,target)
  print(error)
  err.append(error)
  lr=1e-5
  error.backward()
  with torch.no_grad():
    w-=w.grad*lr
    b-=b.grad*lr
    w.grad.zero_()
    b.grad.zero_()

tensor(0.3463, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3455, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3447, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3440, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3433, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3425, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3418, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3411, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3405, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3398, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3391, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3385, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3379, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3372, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3366, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3360, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3354, dtype=torch.float64, grad

In [501]:
error

tensor(0.3018, dtype=torch.float64, grad_fn=<DivBackward0>)

In [497]:
w

tensor([[-0.3004, -0.0836,  0.2550,  0.5295,  0.3258,  0.9929]],
       dtype=torch.float64, requires_grad=True)

In [498]:
pred

tensor([[13.7333],
        [14.1011],
        [14.1311],
        ...,
        [13.4315],
        [14.2608],
        [14.2075]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [499]:
target

tensor([13.8729, 14.2249, 13.8728,  ..., 13.8458, 13.9967, 14.0771],
       dtype=torch.float64)

In [502]:
pred=torch.exp(pred)

In [503]:
target=torch.exp(target)

In [504]:
pred

tensor([[ 921097.8297],
        [1330558.1835],
        [1371089.8278],
        ...,
        [ 681150.0225],
        [1560947.1059],
        [1479929.4280]], dtype=torch.float64, grad_fn=<ExpBackward>)

In [505]:
target

tensor([1059033.5579, 1505890.9148, 1058987.9879,  ..., 1030729.5832,
        1198656.8724, 1298950.4803], dtype=torch.float64)

The predictions are very similar to target values and the error is also less.

In [508]:
print(torch.exp(error))

tensor(3.8664, dtype=torch.float64, grad_fn=<ExpBackward>)


In [514]:
new=prediction(torch.tensor([[23,14,25,78.9,56,12]],dtype=torch.float64))

In [516]:
print(new)

tensor([[69.2135]], dtype=torch.float64, grad_fn=<AddBackward0>)


In [517]:
jovian.commit(project='linear-regression')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rhuthuhegde/linear-regression


'https://jovian.ai/rhuthuhegde/linear-regression'